version: '3.7'
services:
  postgres:
    image: postgres:15.6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gpt_ace
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      # initial db in order
      - ../db/migrations/:/docker-entrypoint-initdb.d/
      # - ./postgres-data:/var/lib/postgresql/data
