---
# - name: Ensure dirmngr is installed (gnupg dependency).
#   apt:
#     name: dirmngr
#     state: present

- name: Ensure dirmngr is installed (gnupg dependency).
  ansible.builtin.apt:
    name: "dirmngr"
    update_cache: yes

- name: Add PPA for Nginx (if configured).
  apt_repository:
    repo: 'ppa:nginx/{{ nginx_ppa_version }}'
    state: present
    update_cache: true
  register: nginx_ppa_added
  when: nginx_ppa_use | bool

- name: Ensure nginx will reinstall if the PPA was just added.
  apt:
    name: "{{ nginx_package_name }}"
    state: absent
  when: nginx_ppa_added is changed
  tags: ['skip_ansible_lint']
