---
- name: Remove externally managed from Debian 12
  ansible.builtin.import_tasks: debian12.yml
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version|int >= 12

- name: Ensure Pip is installed.
  ansible.builtin.apt:
    name: "{{ pip_package }}"
    update_cache: yes

- name: fix issue at installing docker-compose in debian 12.1 system. It must be run before install pip package of docker-compose
  ansible.builtin.pip:
    name: pyyaml==5.3.1
    state: present

- name: Ensure pip_install_packages are installed.
  ansible.builtin.pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    extra_args: "{{ item.extra_args | default(omit) }}"
    executable: "{{ pip_executable }}"
  loop: "{{ pip_install_packages }}"
